### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by zertyz** [obiwankennedy/pses#2]
I'm new to Qt... If this is a naive issue, maybe a little doc would help:

$ qmake
Info: creating stash file /home/luiz/Downloads/t/pses/.qmake.stash
Cannot read /home/luiz/Downloads/t/pses/DiceParser/diceparser.pri: No such file or directory

**Comment by zertyz** [comment]
oh, that was an unitialized submodule issue. Anyway, that info could be on the README.

Something like:

- Clone this project with git clone --recurse-submodules 'https://github.com/obiwankennedy/pses.git'
- Build it with qmake; make

**Comment by obiwankennedy** [comment]
Hi, You are right. I did not expect many people to compile that project. It is an old slide presentation. 

I recommand you to use the pycon2018 branch if you want to make upir own slide presentation.

**Comment by zertyz** [comment]
great! thank you for that info.
